<H1>The First ML Tutorial</H1>

To do analysis, you need some data. Hence download some dataset from the Internet.

1. Download the Automobile dataset from <a href="https://archive.ics.uci.edu/ml/datasets/Automobile">here</a>
2. Download the German Credit dataset from <a href="https://archive.ics.uci.edu/ml/datasets/Statlog+%28German+Credit+Data%29">here</a>
3. Download the Wine Quality dataset (White Wine) from <a href="https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv">here</a>

<H2>Your tasks are as follows</H2>

1. Download the datasets and store them in a file named "Datasets" in your computer
2. Read the datasets using 'pandas'
3. Put all the datasets in a single dictionary named 'all_datasets' in python
4. Produce an output which would show the number of rows and number of columns of each dataset
5. Extract the datatypes of each variable in each dataset. Are they all belonging to correct datatypes?
6. Do you think that some of the variables are containing missing values? Which are those variables? How many missing values are there in each variable in each dataset?
7. Replace the missing values with 'NAN'(actually, numpy.nan)
8. Take out a random sample from the wine quality dataset containing 500 rows and name it as 'wq_rand'. What will you do to get same result in each run?
9. Extract coefficient of variation (CV) for each variable in 'wq_rand' dataset. CV is (mean/standard deviation)
10. Create a new array with 500 random numbers generating from a normal distribution having mean 10 and standard deviation 8. Sort the array and attach the sorted array to the 'wq_rand' dataset
11. Sort the wq_rand dataset with respect to pH variable
12. Create a new dataset from Automobile dataset such that it does not contain any missing value. Name it as auto_cleaned.
13. From auto_cleaned dataset retain only numeric variables and run a PCA retaining 5 components. What proportion of total variance is being explained by those 5 components? How will you extract components such that the explained variance by the components is at least 80%?

In [1]:
import pandas as pd
import numpy as np

In [2]:
#Q2
df_auto = pd.read_csv("C:\\Users\\Umang\\Downloads\\Datasets\\Auto.txt", sep=",", header=None, na_values="?")
df_auto.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

In [3]:
#Q2
df_germen = pd.read_csv("C:\\Users\\Umang\\Downloads\\Datasets\\german.data.txt", header=None, sep=" ")
df_germen.head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,1
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,2
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,1
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,1
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,2

In [4]:
#Q2
df_wine = pd.read_csv("C:\\Users\\Umang\\Downloads\\Datasets\\winequality-white.csv", sep=";")
df_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [5]:
#Q3
all_datasets= {'auto':df_auto, 'germen':df_germen, 'wine':df_wine}
all_datasets

{'auto':      0      1            2       3      4     5            6    7      8   \
 0     3    NaN  alfa-romero     gas    std   two  convertible  rwd  front
 1     3    NaN  alfa-romero     gas    std   two  convertible  rwd  front
 2     1    NaN  alfa-romero     gas    std   two    hatchback  rwd  front
 3     2  164.0         audi     gas    std  four        sedan  fwd  front
 4     2  164.0         audi     gas    std  four        sedan  4wd  front
 5     2    NaN         audi     gas    std   two        sedan  fwd  front
 6     1  158.0         audi     gas    std  four        sedan  fwd  front
 7     1    NaN         audi     gas    std  four        wagon  fwd  front
 8     1  158.0         audi     gas  turbo  four        sedan  fwd  front
 9     0    NaN         audi     gas  turbo   two    hatchback  4wd  front
 10    2  192.0          bmw     gas    std   two        sedan  rwd  front
 11    0  192.0          bmw     gas    std  four        sedan  rwd  front
 12    0  188.0          bmw     gas    std   two        sedan  rwd  front
 13    0  188.0          bmw     gas    std  four        sedan  rwd  front
 14    1    NaN          bmw     gas    std  four        sedan  rwd  front
 15    0    NaN          bmw     gas    std  four        sedan  rwd  front
 16    0    NaN          bmw     gas    std   two        sedan  rwd  front
 17    0    NaN          bmw     gas    std  four        sedan  rwd  front
 18    2  121.0    chevrolet     gas    std   two    hatchback  fwd  front
 19    1   98.0    chevrolet     gas    std   two    hatchback  fwd  front
 20    0   81.0    chevrolet     gas    std  four        sedan  fwd  front
 21    1  118.0        dodge     gas    std   two    hatchback  fwd  front
 22    1  118.0        dodge     gas    std   two    hatchback  fwd  front
 23    1  118.0        dodge     gas  turbo   two    hatchback  fwd  front
 24    1  148.0        dodge     gas    std  four    hatchback  fwd  front
 25    1  148.0        dodge     gas    std  four        sedan  fwd  front
 26    1  148.0        dodge     gas    std  four        sedan  fwd  front
 27    1  148.0        dodge     gas  turbo   NaN        sedan  fwd  front
 28   -1  110.0        dodge     gas    std  four        wagon  fwd  front
 29    3  145.0        dodge     gas  turbo   two    hatchback  fwd  front
 ..   ..    ...          ...     ...    ...   ...          ...  ...    ...
 175  -1   65.0       toyota     gas    std  four    hatchback  fwd  front
 176  -1   65.0       toyota     gas    std  four        sedan  fwd  front
 177  -1   65.0       toyota     gas    std  four    hatchback  fwd  front
 178   3  197.0       toyota     gas    std   two    hatchback  rwd  front
 179   3  197.0       toyota     gas    std   two    hatchback  rwd  front
 180  -1   90.0       toyota     gas    std  four        sedan  rwd  front
 181  -1    NaN       toyota     gas    std  four        wagon  rwd  front
 182   2  122.0   volkswagen  diesel    std   two        sedan  fwd  front
 183   2  122.0   volkswagen     gas    std   two        sedan  fwd  front
 184   2   94.0   volkswagen  diesel    std  four        sedan  fwd  front
 185   2   94.0   volkswagen     gas    std  four        sedan  fwd  front
 186   2   94.0   volkswagen     gas    std  four        sedan  fwd  front
 187   2   94.0   volkswagen  diesel  turbo  four        sedan  fwd  front
 188   2   94.0   volkswagen     gas    std  four        sedan  fwd  front
 189   3    NaN   volkswagen     gas    std   two  convertible  fwd  front
 190   3  256.0   volkswagen     gas    std   two    hatchback  fwd  front
 191   0    NaN   volkswagen     gas    std  four        sedan  fwd  front
 192   0    NaN   volkswagen  diesel  turbo  four        sedan  fwd  front
 193   0    NaN   volkswagen     gas    std  four        wagon  fwd  front
 194  -2  103.0        volvo     gas    std  four        sedan  rwd  front
 195  -1   74.0        volvo     gas    std  four        wagon  rwd  front
 196  -2  103.0        volvo     gas    std  four        sedan  rwd  front
 197  -1   74.0        volvo     gas    std  four        wagon  rwd  front
 198  -2  103.0        volvo     gas  turbo  four        sedan  rwd  front
 199  -1   74.0        volvo     gas  turbo  four        wagon  rwd  front
 200  -1   95.0        volvo     gas    std  four        sedan  rwd  front
 201  -1   95.0        volvo     gas  turbo  four        sedan  rwd  front
 202  -1   95.0        volvo     gas    std  four        sedan  rwd  front
 203  -1   95.0        volvo  diesel  turbo  four        sedan  rwd  front
 204  -1   95.0        volvo     gas  turbo  four        sedan  rwd  front

         9    ...      16    17    18    19     20     21      22  23  24  \
 0     88.6   ...     130  mpfi  3.47  2.68   9.00  111.0  5000.0  21  27
 1     88.6   ...     130  mpfi  3.47  2.68   9.00  111.0  5000.0  21  27
 2     94.5   ...     152  mpfi  2.68  3.47   9.00  154.0  5000.0  19  26
 3     99.8   ...     109  mpfi  3.19  3.40  10.00  102.0  5500.0  24  30
 4     99.4   ...     136  mpfi  3.19  3.40   8.00  115.0  5500.0  18  22
 5     99.8   ...     136  mpfi  3.19  3.40   8.50  110.0  5500.0  19  25
 6    105.8   ...     136  mpfi  3.19  3.40   8.50  110.0  5500.0  19  25
 7    105.8   ...     136  mpfi  3.19  3.40   8.50  110.0  5500.0  19  25
 8    105.8   ...     131  mpfi  3.13  3.40   8.30  140.0  5500.0  17  20
 9     99.5   ...     131  mpfi  3.13  3.40   7.00  160.0  5500.0  16  22
 10   101.2   ...     108  mpfi  3.50  2.80   8.80  101.0  5800.0  23  29
 11   101.2   ...     108  mpfi  3.50  2.80   8.80  101.0  5800.0  23  29
 12   101.2   ...     164  mpfi  3.31  3.19   9.00  121.0  4250.0  21  28
 13   101.2   ...     164  mpfi  3.31  3.19   9.00  121.0  4250.0  21  28
 14   103.5   ...     164  mpfi  3.31  3.19   9.00  121.0  4250.0  20  25
 15   103.5   ...     209  mpfi  3.62  3.39   8.00  182.0  5400.0  16  22
 16   103.5   ...     209  mpfi  3.62  3.39   8.00  182.0  5400.0  16  22
 17   110.0   ...     209  mpfi  3.62  3.39   8.00  182.0  5400.0  15  20
 18    88.4   ...      61  2bbl  2.91  3.03   9.50   48.0  5100.0  47  53
 19    94.5   ...      90  2bbl  3.03  3.11   9.60   70.0  5400.0  38  43
 20    94.5   ...      90  2bbl  3.03  3.11   9.60   70.0  5400.0  38  43
 21    93.7   ...      90  2bbl  2.97  3.23   9.41   68.0  5500.0  37  41
 22    93.7   ...      90  2bbl  2.97  3.23   9.40   68.0  5500.0  31  38
 23    93.7   ...      98  mpfi  3.03  3.39   7.60  102.0  5500.0  24  30
 24    93.7   ...      90  2bbl  2.97  3.23   9.40   68.0  5500.0  31  38
 25    93.7   ...      90  2bbl  2.97  3.23   9.40   68.0  5500.0  31  38
 26    93.7   ...      90  2bbl  2.97  3.23   9.40   68.0  5500.0  31  38
 27    93.7   ...      98  mpfi  3.03  3.39   7.60  102.0  5500.0  24  30
 28   103.3   ...     122  2bbl  3.34  3.46   8.50   88.0  5000.0  24  30
 29    95.9   ...     156   mfi  3.60  3.90   7.00  145.0  5000.0  19  24
 ..     ...   ...     ...   ...   ...   ...    ...    ...     ...  ..  ..
 175  102.4   ...     122  mpfi  3.31  3.54   8.70   92.0  4200.0  27  32
 176  102.4   ...     122  mpfi  3.31  3.54   8.70   92.0  4200.0  27  32
 177  102.4   ...     122  mpfi  3.31  3.54   8.70   92.0  4200.0  27  32
 178  102.9   ...     171  mpfi  3.27  3.35   9.30  161.0  5200.0  20  24
 179  102.9   ...     171  mpfi  3.27  3.35   9.30  161.0  5200.0  19  24
 180  104.5   ...     171  mpfi  3.27  3.35   9.20  156.0  5200.0  20  24
 181  104.5   ...     161  mpfi  3.27  3.35   9.20  156.0  5200.0  19  24
 182   97.3   ...      97   idi  3.01  3.40  23.00   52.0  4800.0  37  46
 183   97.3   ...     109  mpfi  3.19  3.40   9.00   85.0  5250.0  27  34
 184   97.3   ...      97   idi  3.01  3.40  23.00   52.0  4800.0  37  46
 185   97.3   ...     109  mpfi  3.19  3.40   9.00   85.0  5250.0  27  34
 186   97.3   ...     109  mpfi  3.19  3.40   9.00   85.0  5250.0  27  34
 187   97.3   ...      97   idi  3.01  3.40  23.00   68.0  4500.0  37  42
 188   97.3   ...     109  mpfi  3.19  3.40  10.00  100.0  5500.0  26  32
 189   94.5   ...     109  mpfi  3.19  3.40   8.50   90.0  5500.0  24  29
 190   94.5   ...     109  mpfi  3.19  3.40   8.50   90.0  5500.0  24  29
 191  100.4   ...     136  mpfi  3.19  3.40   8.50  110.0  5500.0  19  24
 192  100.4   ...      97   idi  3.01  3.40  23.00   68.0  4500.0  33  38
 193  100.4   ...     109  mpfi  3.19  3.40   9.00   88.0  5500.0  25  31
 194  104.3   ...     141  mpfi  3.78  3.15   9.50  114.0  5400.0  23  28
 195  104.3   ...     141  mpfi  3.78  3.15   9.50  114.0  5400.0  23  28
 196  104.3   ...     141  mpfi  3.78  3.15   9.50  114.0  5400.0  24  28
 197  104.3   ...     141  mpfi  3.78  3.15   9.50  114.0  5400.0  24  28
 198  104.3   ...     130  mpfi  3.62  3.15   7.50  162.0  5100.0  17  22
 199  104.3   ...     130  mpfi  3.62  3.15   7.50  162.0  5100.0  17  22
 200  109.1   ...     141  mpfi  3.78  3.15   9.50  114.0  5400.0  23  28
 201  109.1   ...     141  mpfi  3.78  3.15   8.70  160.0  5300.0  19  25
 202  109.1   ...     173  mpfi  3.58  2.87   8.80  134.0  5500.0  18  23
 203  109.1   ...     145   idi  3.01  3.40  23.00  106.0  4800.0  26  27
 204  109.1   ...     141  mpfi  3.78  3.15   9.50  114.0  5400.0  19  25

           25
 0    13495.0
 1    16500.0
 2    16500.0
 3    13950.0
 4    17450.0
 5    15250.0
 6    17710.0
 7    18920.0
 8    23875.0
 9        NaN
 10   16430.0
 11   16925.0
 12   20970.0
 13   21105.0
 14   24565.0
 15   30760.0
 16   41315.0
 17   36880.0
 18    5151.0
 19    6295.0
 20    6575.0
 21    5572.0
 22    6377.0
 23    7957.0
 24    6229.0
 25    6692.0
 26    7609.0
 27    8558.0
 28    8921.0
 29   12964.0
 ..       ...
 175   9988.0
 176  10898.0
 177  11248.0
 178  16558.0
 179  15998.0
 180  15690.0
 181  15750.0
 182   7775.0
 183   7975.0
 184   7995.0
 185   8195.0
 186   8495.0
 187   9495.0
 188   9995.0
 189  11595.0
 190   9980.0
 191  13295.0
 192  13845.0
 193  12290.0
 194  12940.0
 195  13415.0
 196  15985.0
 197  16515.0
 198  18420.0
 199  18950.0
 200  16845.0
 201  19045.0
 202  21485.0
 203  22470.0
 204  22625.0

 [205 rows x 26 columns],
 'germen':       0   1    2    3      4    5    6   7    8     9  ...    11  12    13  \
 0    A11   6  A34  A43   1169  A65  A75   4  A93  A101 ...  A121  67  A143
 1    A12  48  A32  A43   5951  A61  A73   2  A92  A101 ...  A121  22  A143
 2    A14  12  A34  A46   2096  A61  A74   2  A93  A101 ...  A121  49  A143
 3    A11  42  A32  A42   7882  A61  A74   2  A93  A103 ...  A122  45  A143
 4    A11  24  A33  A40   4870  A61  A73   3  A93  A101 ...  A124  53  A143
 5    A14  36  A32  A46   9055  A65  A73   2  A93  A101 ...  A124  35  A143
 6    A14  24  A32  A42   2835  A63  A75   3  A93  A101 ...  A122  53  A143
 7    A12  36  A32  A41   6948  A61  A73   2  A93  A101 ...  A123  35  A143
 8    A14  12  A32  A43   3059  A64  A74   2  A91  A101 ...  A121  61  A143
 9    A12  30  A34  A40   5234  A61  A71   4  A94  A101 ...  A123  28  A143
 10   A12  12  A32  A40   1295  A61  A72   3  A92  A101 ...  A123  25  A143
 11   A11  48  A32  A49   4308  A61  A72   3  A92  A101 ...  A122  24  A143
 12   A12  12  A32  A43   1567  A61  A73   1  A92  A101 ...  A123  22  A143
 13   A11  24  A34  A40   1199  A61  A75   4  A93  A101 ...  A123  60  A143
 14   A11  15  A32  A40   1403  A61  A73   2  A92  A101 ...  A123  28  A143
 15   A11  24  A32  A43   1282  A62  A73   4  A92  A101 ...  A123  32  A143
 16   A14  24  A34  A43   2424  A65  A75   4  A93  A101 ...  A122  53  A143
 17   A11  30  A30  A49   8072  A65  A72   2  A93  A101 ...  A123  25  A141
 18   A12  24  A32  A41  12579  A61  A75   4  A92  A101 ...  A124  44  A143
 19   A14  24  A32  A43   3430  A63  A75   3  A93  A101 ...  A123  31  A143
 20   A14   9  A34  A40   2134  A61  A73   4  A93  A101 ...  A123  48  A143
 21   A11   6  A32  A43   2647  A63  A73   2  A93  A101 ...  A121  44  A143
 22   A11  10  A34  A40   2241  A61  A72   1  A93  A101 ...  A121  48  A143
 23   A12  12  A34  A41   1804  A62  A72   3  A93  A101 ...  A122  44  A143
 24   A14  10  A34  A42   2069  A65  A73   2  A94  A101 ...  A123  26  A143
 25   A11   6  A32  A42   1374  A61  A73   1  A93  A101 ...  A121  36  A141
 26   A14   6  A30  A43    426  A61  A75   4  A94  A101 ...  A123  39  A143
 27   A13  12  A31  A43    409  A64  A73   3  A92  A101 ...  A121  42  A143
 28   A12   7  A32  A43   2415  A61  A73   3  A93  A103 ...  A121  34  A143
 29   A11  60  A33  A49   6836  A61  A75   3  A93  A101 ...  A124  63  A143
 ..   ...  ..  ...  ...    ...  ...  ...  ..  ...   ... ...   ...  ..   ...
 970  A12  15  A32  A45   1514  A62  A73   4  A93  A103 ...  A121  22  A143
 971  A14  24  A32  A40   7393  A61  A73   1  A93  A101 ...  A122  43  A143
 972  A11  24  A31  A40   1193  A61  A71   1  A92  A102 ...  A124  29  A143
 973  A11  60  A32  A49   7297  A61  A75   4  A93  A102 ...  A124  36  A143
 974  A14  30  A34  A43   2831  A61  A73   4  A92  A101 ...  A123  33  A143
 975  A13  24  A32  A43   1258  A63  A73   3  A92  A101 ...  A123  57  A143
 976  A12   6  A32  A43    753  A61  A73   2  A92  A103 ...  A121  64  A143
 977  A12  18  A33  A49   2427  A65  A75   4  A93  A101 ...  A122  42  A143
 978  A14  24  A33  A40   2538  A61  A75   4  A93  A101 ...  A123  47  A143
 979  A12  15  A31  A40   1264  A62  A73   2  A94  A101 ...  A122  25  A143
 980  A12  30  A34  A42   8386  A61  A74   2  A93  A101 ...  A122  49  A143
 981  A14  48  A32  A49   4844  A61  A71   3  A93  A101 ...  A123  33  A141
 982  A13  21  A32  A40   2923  A62  A73   1  A92  A101 ...  A123  28  A141
 983  A11  36  A32  A41   8229  A61  A73   2  A93  A101 ...  A122  26  A143
 984  A14  24  A34  A42   2028  A61  A74   2  A93  A101 ...  A122  30  A143
 985  A11  15  A34  A42   1433  A61  A73   4  A92  A101 ...  A122  25  A143
 986  A13  42  A30  A49   6289  A61  A72   2  A91  A101 ...  A122  33  A143
 987  A14  13  A32  A43   1409  A62  A71   2  A92  A101 ...  A121  64  A143
 988  A11  24  A32  A41   6579  A61  A71   4  A93  A101 ...  A124  29  A143
 989  A12  24  A34  A43   1743  A61  A75   4  A93  A101 ...  A122  48  A143
 990  A14  12  A34  A46   3565  A65  A72   2  A93  A101 ...  A122  37  A143
 991  A14  15  A31  A43   1569  A62  A75   4  A93  A101 ...  A123  34  A141
 992  A11  18  A32  A43   1936  A65  A74   2  A94  A101 ...  A123  23  A143
 993  A11  36  A32  A42   3959  A61  A71   4  A93  A101 ...  A122  30  A143
 994  A14  12  A32  A40   2390  A65  A75   4  A93  A101 ...  A123  50  A143
 995  A14  12  A32  A42   1736  A61  A74   3  A92  A101 ...  A121  31  A143
 996  A11  30  A32  A41   3857  A61  A73   4  A91  A101 ...  A122  40  A143
 997  A14  12  A32  A43    804  A61  A75   4  A93  A101 ...  A123  38  A143
 998  A11  45  A32  A43   1845  A61  A73   4  A93  A101 ...  A124  23  A143
 999  A12  45  A34  A41   4576  A62  A71   3  A93  A101 ...  A123  27  A143

        14 15    16 17    18    19 20
 0    A152  2  A173  1  A192  A201  1
 1    A152  1  A173  1  A191  A201  2
 2    A152  1  A172  2  A191  A201  1
 3    A153  1  A173  2  A191  A201  1
 4    A153  2  A173  2  A191  A201  2
 5    A153  1  A172  2  A192  A201  1
 6    A152  1  A173  1  A191  A201  1
 7    A151  1  A174  1  A192  A201  1
 8    A152  1  A172  1  A191  A201  1
 9    A152  2  A174  1  A191  A201  2
 10   A151  1  A173  1  A191  A201  2
 11   A151  1  A173  1  A191  A201  2
 12   A152  1  A173  1  A192  A201  1
 13   A152  2  A172  1  A191  A201  2
 14   A151  1  A173  1  A191  A201  1
 15   A152  1  A172  1  A191  A201  2
 16   A152  2  A173  1  A191  A201  1
 17   A152  3  A173  1  A191  A201  1
 18   A153  1  A174  1  A192  A201  2
 19   A152  1  A173  2  A192  A201  1
 20   A152  3  A173  1  A192  A201  1
 21   A151  1  A173  2  A191  A201  1
 22   A151  2  A172  2  A191  A202  1
 23   A152  1  A173  1  A191  A201  1
 24   A152  2  A173  1  A191  A202  1
 25   A152  1  A172  1  A192  A201  1
 26   A152  1  A172  1  A191  A201  1
 27   A151  2  A173  1  A191  A201  1
 28   A152  1  A173  1  A191  A201  1
 29   A152  2  A173  1  A192  A201  2
 ..    ... ..   ... ..   ...   ... ..
 970  A152  1  A173  1  A191  A201  1
 971  A152  1  A172  2  A191  A201  1
 972  A151  2  A171  1  A191  A201  2
 973  A151  1  A173  1  A191  A201  2
 974  A152  1  A173  1  A192  A201  1
 975  A152  1  A172  1  A191  A201  1
 976  A152  1  A173  1  A191  A201  1
 977  A152  2  A173  1  A191  A201  1
 978  A152  2  A172  2  A191  A201  2
 979  A151  1  A173  1  A191  A201  2
 980  A152  1  A173  1  A191  A201  2
 981  A151  1  A174  1  A192  A201  2
 982  A152  1  A174  1  A192  A201  1
 983  A152  1  A173  2  A191  A201  2
 984  A152  2  A172  1  A191  A201  1
 985  A151  2  A173  1  A191  A201  1
 986  A152  2  A173  1  A191  A201  1
 987  A152  1  A173  1  A191  A201  1
 988  A153  1  A174  1  A192  A201  1
 989  A152  2  A172  1  A191  A201  1
 990  A152  2  A172  2  A191  A201  1
 991  A152  1  A172  2  A191  A201  1
 992  A151  2  A172  1  A191  A201  1
 993  A152  1  A174  1  A192  A201  1
 994  A152  1  A173  1  A192  A201  1
 995  A152  1  A172  1  A191  A201  1
 996  A152  1  A174  1  A192  A201  1
 997  A152  1  A173  1  A191  A201  1
 998  A153  1  A173  1  A192  A201  2
 999  A152  1  A173  1  A191  A201  1

 [1000 rows x 21 columns],
 'wine':       fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
 0               7.0             0.270         0.36           20.70      0.045
 1               6.3             0.300         0.34            1.60      0.049
 2               8.1             0.280         0.40            6.90      0.050
 3               7.2             0.230         0.32            8.50      0.058
 4               7.2             0.230         0.32            8.50      0.058
 5               8.1             0.280         0.40            6.90      0.050
 6               6.2             0.320         0.16            7.00      0.045
 7               7.0             0.270         0.36           20.70      0.045
 8               6.3             0.300         0.34            1.60      0.049
 9               8.1             0.220         0.43            1.50      0.044
 10              8.1             0.270         0.41            1.45      0.033
 11              8.6             0.230         0.40            4.20      0.035
 12              7.9             0.180         0.37            1.20      0.040
 13              6.6             0.160         0.40            1.50      0.044
 14              8.3             0.420         0.62           19.25      0.040
 15              6.6             0.170         0.38            1.50      0.032
 16              6.3             0.480         0.04            1.10      0.046
 17              6.2             0.660         0.48            1.20      0.029
 18              7.4             0.340         0.42            1.10      0.033
 19              6.5             0.310         0.14            7.50      0.044
 20              6.2             0.660         0.48            1.20      0.029
 21              6.4             0.310         0.38            2.90      0.038
 22              6.8             0.260         0.42            1.70      0.049
 23              7.6             0.670         0.14            1.50      0.074
 24              6.6             0.270         0.41            1.30      0.052
 25              7.0             0.250         0.32            9.00      0.046
 26              6.9             0.240         0.35            1.00      0.052
 27              7.0             0.280         0.39            8.70      0.051
 28              7.4             0.270         0.48            1.10      0.047
 29              7.2             0.320         0.36            2.00      0.033
 ...             ...               ...          ...             ...        ...
 4868            5.8             0.230         0.31            4.50      0.046
 4869            6.6             0.240         0.33           10.10      0.032

In [6]:
#Q4
for i in all_datasets:
    print("no of rows and columns in dataset", i , "is: ", all_datasets[i].shape)

no of rows and columns in dataset auto is:  (205, 26)
no of rows and columns in dataset germen is:  (1000, 21)
no of rows and columns in dataset wine is:  (4898, 12)

In [7]:
all_datasets.keys()

dict_keys(['auto', 'germen', 'wine'])

In [8]:
#Q5
for i in all_datasets:
    print( all_datasets[i].dtypes)

0       int64
1     float64
2      object
3      object
4      object
5      object
6      object
7      object
8      object
9     float64
10    float64
11    float64
12    float64
13      int64
14     object
15     object
16      int64
17     object
18    float64
19    float64
20    float64
21    float64
22    float64
23      int64
24      int64
25    float64
dtype: object
0     object
1      int64
2     object
3     object
4      int64
5     object
6     object
7      int64
8     object
9     object
10     int64
11    object
12     int64
13    object
14    object
15     int64
16    object
17     int64
18    object
19    object
20     int64
dtype: object
fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [13]:
#Q6
for i in all_datasets:
    print(all_datasets[i].isnull().sum())
#df_auto.isnull().sum()

0      0
1     41
2      0
3      0
4      0
5      2
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     4
19     4
20     0
21     2
22     2
23     0
24     0
25     4
dtype: int64
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
dtype: int64
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [ ]:
#Q7 is allready taken care off while reading the dataset

In [14]:
#Q8
wq_rand=df_wine.sample(n=500, random_state=1234)
print(wq_rand.shape)
wq_rand.head()

(500, 12)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1431,6.1,0.22,0.49,1.5,0.051,18.0,87.0,0.99280,3.30,0.46,9.6,5
445,7.1,0.32,0.32,11.0,0.038,16.0,66.0,0.99370,3.24,0.40,11.5,3
2816,7.2,0.17,0.41,1.6,0.052,24.0,126.0,0.99228,3.19,0.49,10.8,5
4049,6.8,0.16,0.36,1.3,0.034,32.0,98.0,0.99058,3.02,0.58,11.3,6
4779,6.0,0.59,0.00,0.8,0.037,30.0,95.0,0.99032,3.10,0.40,10.9,4

In [15]:
#Q9
def cv(inp):
    return(inp.std()/inp.mean())

wq_rand.apply(cv,axis=0)

fixed acidity           0.128724
volatile acidity        0.357739
citric acid             0.378508
residual sugar          0.886916
chlorides               0.585182
free sulfur dioxide     0.464603
total sulfur dioxide    0.326143
density                 0.003529
pH                      0.047368
sulphates               0.226209
alcohol                 0.113540
quality                 0.153703
dtype: float64

In [16]:
#Q9
CV = wq_rand.std()/wq_rand.mean()
CV

fixed acidity           0.128724
volatile acidity        0.357739
citric acid             0.378508
residual sugar          0.886916
chlorides               0.585182
free sulfur dioxide     0.464603
total sulfur dioxide    0.326143
density                 0.003529
pH                      0.047368
sulphates               0.226209
alcohol                 0.113540
quality                 0.153703
dtype: float64

In [17]:
#Q10
np.random.seed(seed=1234)
new_array = np.random.normal(10,8,500)
print(new_array.mean())
print(new_array.std())

10.0778503119
7.67621898918

In [18]:
new_array.sort()
len(new_array)

500

In [19]:
wq_rand.shape
wq_rand['attach']=new_array
wq_rand.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,attach
1431,6.1,0.22,0.49,1.5,0.051,18.0,87.0,0.99280,3.30,0.46,9.6,5,-18.508133
445,7.1,0.32,0.32,11.0,0.038,16.0,66.0,0.99370,3.24,0.40,11.5,3,-9.203629
2816,7.2,0.17,0.41,1.6,0.052,24.0,126.0,0.99228,3.19,0.49,10.8,5,-9.180032
4049,6.8,0.16,0.36,1.3,0.034,32.0,98.0,0.99058,3.02,0.58,11.3,6,-7.941480
4779,6.0,0.59,0.00,0.8,0.037,30.0,95.0,0.99032,3.10,0.40,10.9,4,-7.808941

In [20]:
#Q11
wq_rand.sort_values('pH').head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,attach
3831,6.8,0.31,0.19,3.5,0.086,30.0,130.0,0.99300,2.83,0.44,9.6,5,7.087920
3094,9.7,0.24,0.49,4.9,0.032,3.0,18.0,0.99368,2.85,0.54,10.0,6,13.588078
3095,9.7,0.24,0.49,4.9,0.032,3.0,18.0,0.99368,2.85,0.54,10.0,6,20.179161
4688,6.7,0.16,0.32,12.5,0.035,18.0,156.0,0.99666,2.88,0.36,9.0,6,2.307182
156,7.4,0.24,0.42,14.0,0.066,48.0,198.0,0.99790,2.89,0.42,8.9,6,15.347905
155,7.4,0.24,0.42,14.0,0.066,48.0,198.0,0.99790,2.89,0.42,8.9,6,12.652212
3747,6.8,0.22,0.30,10.6,0.070,67.0,194.0,0.99654,2.89,0.42,9.0,6,5.058347
2462,8.3,0.25,0.33,2.5,0.053,12.0,72.0,0.99404,2.89,0.48,9.5,5,16.876707
4042,7.4,0.16,0.27,15.5,0.050,25.0,135.0,0.99840,2.90,0.43,8.7,7,2.822746
3307,9.4,0.24,0.29,8.5,0.037,124.0,208.0,0.99395,2.90,0.38,11.0,3,2.824767

In [21]:
#Q12
auto_cleaned = df_auto.dropna()

In [22]:
auto_cleaned.shape

(159, 26)

In [23]:
auto_cleaned.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115.0,5500.0,18,22,17450.0
6,1,158.0,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110.0,5500.0,19,25,17710.0
8,1,158.0,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140.0,5500.0,17,20,23875.0
10,2,192.0,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.8,8.8,101.0,5800.0,23,29,16430.0

In [24]:
auto_cleaned.dtypes

0       int64
1     float64
2      object
3      object
4      object
5      object
6      object
7      object
8      object
9     float64
10    float64
11    float64
12    float64
13      int64
14     object
15     object
16      int64
17     object
18    float64
19    float64
20    float64
21    float64
22    float64
23      int64
24      int64
25    float64
dtype: object

In [22]:
#Q13
auto_cleaned_retained = auto_cleaned.select_dtypes(include=['float64','int64'])

In [23]:
auto_cleaned_retained.shape

(159, 16)

In [24]:
auto_cleaned_retained.head()

,0,1,9,10,11,12,13,16,18,19,20,21,22,23,24,25
3,2,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,3.4,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,3.4,8.0,115.0,5500.0,18,22,17450.0
6,1,158.0,105.8,192.7,71.4,55.7,2844,136,3.19,3.4,8.5,110.0,5500.0,19,25,17710.0
8,1,158.0,105.8,192.7,71.4,55.9,3086,131,3.13,3.4,8.3,140.0,5500.0,17,20,23875.0
10,2,192.0,101.2,176.8,64.8,54.3,2395,108,3.50,2.8,8.8,101.0,5800.0,23,29,16430.0

In [25]:
from sklearn import preprocessing

In [26]:
ss = preprocessing.scale(auto_cleaned_retained)
SS = pd.DataFrame(ss)
SS.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,1.062912,1.206222,0.298157,0.364430,0.305113,0.177143,-0.258394,-0.336785,-0.413240,0.556703,-0.041559,0.201279,0.831733,-0.414945,-0.323313,0.427398
1,1.062912,1.206222,0.220504,0.364430,0.408113,0.177143,0.755296,0.552401,-0.413240,0.556703,-0.557392,0.625812,0.831733,-1.402122,-1.565772,1.024734
2,0.222101,1.037394,1.462948,1.766029,2.983113,0.796169,0.796925,0.552401,-0.413240,0.556703,-0.428433,0.462530,0.831733,-1.237593,-1.099850,1.069108
3,0.222101,1.037394,1.462948,1.766029,2.983113,0.884602,1.300648,0.387737,-0.638386,0.556703,-0.480017,1.442223,0.831733,-1.566652,-1.876386,2.121274
4,1.062912,1.994089,0.569942,0.381841,-0.415887,0.177143,-0.137667,-0.369717,0.750015,-1.484399,-0.351058,0.168622,1.477884,-0.579475,-0.478620,0.850653

In [29]:
from sklearn.decomposition import PCA
from scipy.linalg import eig

In [30]:
my_pca = PCA(n_components=5)

In [31]:
PC1 = my_pca.fit_transform(X=SS)

In [32]:
PC1

array([[  3.48216527e-01,   1.31917529e+00,   5.55304332e-01,
         -5.40318351e-01,   1.19575230e+00],
       [  1.95293181e+00,   2.18355097e+00,   1.45801460e-01,
         -6.33684764e-01,   8.18282211e-01],
       [  3.57608768e+00,   8.30515150e-01,   2.16383422e-01,
         -1.14104897e+00,   1.65678127e+00],
       [  4.60996472e+00,   1.33563883e+00,   8.81429467e-02,
         -1.32370959e+00,   1.78281482e+00],
       [  6.03561304e-01,   2.00517555e+00,  -8.50758109e-01,
          8.54544329e-01,   2.04853046e+00],
       [  8.06484964e-01,   1.32821621e+00,  -1.30131279e+00,
          3.09452470e-01,   1.72151010e+00],
       [  2.33876421e+00,   5.69173130e-01,   6.19008358e-01,
          1.12157630e+00,  -2.61302875e-01],
       [  2.38553002e+00,   5.68454704e-01,   6.31466000e-01,
          1.12477006e+00,  -2.52990414e-01],
       [ -7.02813082e+00,  -5.69716465e-01,   7.22218250e-01,
          8.54049394e-01,   2.87012544e-01],
       [ -3.86380672e+00,  -3.14984982e-01,   1.52548579e-01,
         -1.35560501e-01,  -9.43791407e-02],
       [ -3.67214257e+00,  -8.90879132e-01,  -2.08919071e-01,
         -4.92010452e-01,  -3.96244579e-01],
       [ -3.85500292e+00,   3.39515707e-01,   5.08372238e-01,
         -4.54066130e-01,  -1.33796126e-01],
       [ -3.37368215e+00,   6.61699250e-01,   2.03973216e-01,
         -5.16715907e-01,  -1.63684309e-01],
       [ -1.90599345e+00,   1.64170256e+00,  -2.25306704e-01,
         -9.71579466e-01,  -7.96368903e-01],
       [ -3.29468161e+00,   1.06923750e+00,   4.75774117e-01,
         -3.64223899e-01,   1.26464505e-01],
       [ -3.25368825e+00,   1.07202586e+00,   4.90442633e-01,
         -3.61908856e-01,   1.38447541e-01],
       [ -3.20371950e+00,   1.07892179e+00,   5.12157955e-01,
         -3.59582637e-01,   1.57859357e-01],
       [  8.60967102e-01,  -1.83390625e+00,  -1.24224033e+00,
         -1.25678905e+00,   2.35643889e-01],
       [  1.94248918e+00,   2.99588234e+00,   1.50880671e+00,
         -1.52324343e-01,  -2.10392358e+00],
       [ -5.93277109e+00,  -1.37016044e-01,   2.54321136e+00,
          6.74700182e-01,  -7.21961136e-01],
       [ -4.23733567e+00,   2.11708500e+00,   7.21884560e-01,
         -1.04257709e+00,   8.68604960e-03],
       [ -4.34638485e+00,  -3.51810105e-01,   5.24484736e-02,
         -3.06542481e-01,   3.79324246e-01],
       [ -3.18336501e+00,   8.23633014e-01,  -1.75282146e-01,
         -1.77041258e+00,   8.85065192e-02],
       [ -3.13920552e+00,   8.27640745e-01,  -1.58379617e-01,
         -1.76806105e+00,   1.02794629e-01],
       [ -2.33248576e+00,   4.60805767e-02,  -5.65639262e-01,
         -2.17711032e+00,   6.76227715e-01],
       [ -2.31752279e+00,  -9.68312623e-01,  -1.24762676e+00,
         -2.46739256e+00,   9.50651394e-01],
       [ -1.12541290e+00,   2.52465711e-01,  -1.61223589e-01,
         -1.97590026e+00,  -3.03200322e-01],
       [ -1.02204667e+00,   2.59819238e-01,  -1.23882616e-01,
         -1.97010852e+00,  -2.72541410e-01],
       [ -7.75975713e-01,  -2.08610730e-01,  -4.08488009e-01,
         -2.12231160e+00,  -2.40936768e-01],
       [ -1.09426273e+00,  -1.54516260e-01,  -5.48278880e-01,
         -2.10703209e+00,  -3.58869560e-01],
       [  9.19222350e-02,   2.10062580e-01,  -5.77579057e-01,
         -2.19205127e+00,  -2.39061851e-01],
       [ -6.15044955e-01,   1.01790002e+00,   4.63421089e-01,
         -1.28741946e+00,  -7.51829045e-01],
       [  8.54902757e+00,   1.20367074e+00,   2.36515097e+00,
         -1.60331142e+00,  -1.92764078e+00],
       [ -2.64662404e+00,  -1.93668791e-01,  -5.44953993e-01,
          4.96528445e-02,  -1.42461791e-01],
       [ -2.97172968e+00,  -4.34085790e-01,  -2.47244322e-01,
          1.14943271e-01,  -8.72298743e-02],
       [ -2.93000292e+00,  -4.28979320e-01,  -2.29825857e-01,
          1.16978220e-01,  -7.19158151e-02],
       [ -2.67754945e+00,  -3.79371519e-01,  -1.77097756e-01,
          1.42087491e-01,   1.32987413e-01],
       [ -2.58792339e+00,  -3.82837426e-01,  -1.91185988e-01,
          2.09418412e-01,   9.06866294e-02],
       [  2.07721212e-01,  -5.58916622e-02,   2.72296466e-01,
          2.25300996e-01,  -4.81692215e-01],
       [  3.86378782e-01,  -8.89178342e-01,  -2.80507540e-01,
         -1.93419949e-01,  -4.64185886e-01],
       [  3.03081418e-01,  -4.27314795e-02,   3.13737919e-01,
          2.29740344e-01,  -4.44646765e-01],
       [  4.81738987e-01,  -8.76018160e-01,  -2.39066087e-01,
         -1.88980601e-01,  -4.27140435e-01],
       [  5.46978565e-01,  -8.68970866e-01,  -2.12859603e-01,
         -1.85666204e-01,  -4.04483970e-01],
       [  2.64074009e+00,   1.06650906e-01,  -1.01770215e+00,
          3.73483498e-01,  -6.54010081e-01],
       [  5.89412373e+00,  -2.93762811e+00,   2.22595812e+00,
         -2.82963244e-01,   2.70775237e-02],
       [  6.34095811e+00,  -3.30823578e+00,   2.07637723e+00,
         -3.62965457e-01,   5.24903279e-01],
       [  5.54678173e+00,  -2.13449024e+00,   2.71247323e+00,
          1.50485922e-01,  -2.08411875e-01],
       [  7.29058040e+00,  -3.21362790e+00,   2.49243131e+00,
         -4.04034488e-01,   5.66627599e-01],
       [  5.84942972e+00,   3.15999699e+00,   1.56863987e+00,
          1.76132276e+00,  -7.62395740e-01],
       [ -3.75467606e+00,   1.21342340e+00,   1.13521250e+00,
          2.14994419e-02,   5.15083221e-01],
       [ -3.25487944e+00,   1.53381133e+00,   8.36399824e-01,
         -3.95580489e-02,   4.88490793e-01],
       [ -3.18573137e+00,   1.53552974e+00,   8.57869237e-01,
         -3.52298935e-02,   5.04602379e-01],
       [ -1.90143639e+00,   2.20797041e+00,   1.11431989e-01,
         -7.56132303e-01,  -3.61271485e-01],
       [ -5.23935457e-01,   2.93047578e+00,   8.73292715e-01,
         -2.66181116e-01,  -3.02340385e-01],
       [ -6.98424158e-01,   2.07312387e+00,   1.33666971e+00,
          6.86853389e-01,  -8.31394533e-01],
       [ -4.95341378e-01,   6.49680825e-01,   3.72458349e-01,
         -8.88638005e-02,  -1.08875703e+00],
       [ -4.01290106e-01,   6.57444121e-01,   4.07610422e-01,
         -8.37460053e-02,  -1.05938740e+00],
       [ -2.78490835e-01,   1.51340051e+00,  -7.19370681e-02,
         -1.04000015e+00,  -5.42529458e-01],
       [ -8.90130165e-02,   9.83382037e-01,  -4.39420162e-01,
         -1.53068865e+00,  -7.51145733e-01],
       [ -2.53750192e+00,  -1.61979146e-01,  -4.08785729e-02,
         -2.09534392e-01,   1.73811951e-01],
       [ -3.63581519e+00,  -2.62519708e+00,   3.28469606e+00,
          2.40331162e-01,   1.02887867e+00],
       [ -2.45405712e+00,  -1.54245127e-01,  -8.76268792e-03,
         -2.05113694e-01,   2.01032203e-01],
       [ -2.43559184e+00,  -2.28703180e-01,  -4.80557845e-02,
         -2.31399036e-01,   1.42808155e-01],
       [ -2.28850866e+00,  -3.30955572e-01,  -7.12951663e-02,
         -2.80532226e-01,  -1.64188321e-01],
       [ -2.39499195e+00,  -1.50397243e-01,   1.21862896e-02,
         -2.01754015e-01,   2.18064743e-01],
       [ -2.37578549e+00,   5.77123133e-02,   1.74102153e-01,
         -1.43199663e-01,   1.27317397e-02],
       [ -2.37652666e+00,  -2.24855296e-01,  -2.71068070e-02,
         -2.28039357e-01,   1.59840695e-01],
       [ -2.24377420e+00,  -3.26477274e-01,  -5.37137269e-02,
         -2.78209383e-01,  -1.49139297e-01],
       [ -2.46396523e+00,   9.04978395e-01,   7.37488220e-01,
          3.09735161e-01,   5.93913635e-01],
       [ -2.97613778e-01,  -4.03301938e-01,  -2.89200007e-01,
         -8.85720325e-01,  -6.31278522e-01],
       [ -2.80682630e-01,  -3.98096419e-01,  -2.78695801e-01,
         -8.85338781e-01,  -6.20759093e-01],
       [  3.47709170e+00,   9.14954425e-01,  -6.14632859e-01,
         -4.42585936e-01,  -4.98942977e-01],
       [  3.78991905e+00,   4.66858778e-01,  -8.41024689e-01,
         -5.74609324e-01,  -4.44942538e-01],
       [  3.27123834e+00,   4.76976063e-01,  -6.11691825e-01,
         -5.06714816e-01,  -6.53317775e-01],
       [  2.36418326e+00,   4.07971930e+00,   1.60884440e+00,
          1.18410009e+00,  -6.09428785e-01],
       [  3.11297888e+00,   4.69242533e+00,   1.34365118e+00,
          1.05793259e+00,  -8.36184313e-01],
       [  3.38618532e+00,   3.48165610e+00,   1.44952691e+00,
          6.18920021e-01,  -1.52928295e-01],
       [  3.05772392e+00,  -2.21930502e-01,  -8.35690361e-01,
         -9.00364730e-02,   1.11825475e+00],
       [  3.29238043e+00,  -2.62550206e+00,   2.56737851e+00,
          1.05685444e+00,   6.66003634e-01],
       [  3.08473808e+00,  -1.93783454e-01,  -2.44265952e+00,
          2.06202340e+00,   2.43113433e+00],
       [  3.53340860e+00,  -2.59941132e+00,   2.66425831e+00,
          1.06909179e+00,   7.49782970e-01],
       [  3.35487838e+00,  -1.88094048e-01,  -7.14419305e-01,
         -7.51862508e-02,   1.22383798e+00],
       [  3.59062472e+00,  -2.59151521e+00,   2.68912319e+00,
          1.07175540e+00,   7.72010240e-01],
       [  4.07555365e+00,   9.67431371e-01,  -1.11186717e+00,
         -7.05889752e-01,   1.00347886e+00],
       [ -3.82389953e+00,   3.51685585e-01,   5.22016581e-01,
         -4.47507605e-01,  -1.19713549e-01],
       [ -1.90486616e+00,   1.65425783e+00,  -2.17407237e-01,
         -9.66941211e-01,  -7.85628682e-01],
       [ -3.28791787e+00,   1.14456916e+00,   5.23170918e-01,
         -3.36394369e-01,   1.90905835e-01],
       [ -2.95042664e+00,   1.03278601e+00,   4.85315276e-01,
         -3.67049077e-01,   3.79008954e-01],
       [ -2.67288594e+00,   1.05541732e+00,   5.94538990e-01,
         -3.41109071e-01,   3.55673815e-01],
       [  8.29964539e-01,  -2.28761068e+00,  -1.53292247e+00,
         -1.41070704e+00,  -1.62527055e-01],
       [  2.48317594e+00,   3.61727206e+00,   7.94093502e-01,
          1.71430854e+00,  -2.14059514e-01],
       [  1.51180953e+00,   1.18626805e+00,  -3.95124135e-01,
          9.99740767e-01,   1.25971213e+00],
       [  1.59176010e+00,   2.70563071e-01,  -9.77157098e-01,
          5.15680079e-01,   6.06532975e-01],
       [  5.68956583e-01,   1.40072890e+00,  -1.38766158e+00,
          1.84028281e+00,   3.70469486e+00],
       [  1.81890359e+00,   2.93694414e-01,  -8.87455380e-01,
          5.27418924e-01,   6.83484938e-01],
       [  2.58852092e+00,   2.01718506e+00,  -5.66964154e-01,
          5.93424399e-01,   1.35873644e+00],
       [  2.67819668e+00,   1.10160658e+00,  -1.14378128e+00,
          1.10104995e-01,   7.09753990e-01],
       [ -2.61555797e+00,  -3.69608857e-01,  -1.88254386e+00,
          2.87737187e+00,  -1.39975847e-01],
       [ -1.62289948e+00,  -3.20543512e-01,  -1.42046677e+00,
          2.80996173e+00,  -9.97421270e-01],
       [ -1.39510793e+00,  -6.50840158e-01,  -1.60140090e+00,
          2.73742483e+00,  -6.04157151e-01],
       [ -1.12464506e+00,  -9.40827792e-01,  -1.17855529e+00,
          1.90412269e+00,  -5.26022275e-01],
       [ -5.99021512e-01,  -9.69242715e-01,  -1.24680141e+00,
          2.32599669e+00,  -8.76574259e-01],
       [ -2.59937151e-01,  -9.74089610e-02,  -1.73724123e+00,
          1.32871129e+00,  -2.63274813e-01],
       [  2.14966613e-01,  -5.31666588e-01,  -2.06297836e+00,
          1.68294510e+00,  -2.59044390e-01],
       [  4.88709482e-01,  -2.65321038e-01,  -2.05598370e+00,
          1.63807492e+00,  -4.15669728e-01],
       [ -5.28190361e-01,  -8.50177616e-01,  -1.69373998e+00,
          1.75091593e+00,  -6.19612049e-01],
       [ -2.18496527e-02,  -2.85822303e-01,  -1.94739717e+00,
          1.23867352e+00,  -2.87152704e-01],
       [  8.93067588e-02,  -9.50596812e-01,  -2.19458341e+00,
          1.59931786e+00,  -3.19918673e-01],
       [  1.00290701e+00,  -3.76133646e-01,  -2.47075428e+00,
          1.48447436e+00,  -4.73409786e-01],
       [ -3.16316258e+00,  -1.20149295e+00,  -4.01705445e-01,
          5.33500346e-01,  -1.54291039e-01],
       [ -2.82553462e+00,  -1.01555224e+00,  -5.49753764e-01,
          5.03868022e-01,  -1.54385239e-01],
       [ -2.84992904e+00,  -1.17685480e+00,  -6.53104130e-01,
          4.42655177e-01,  -2.93312190e-01],
       [ -1.90978444e+00,  -2.34424258e+00,  -1.40120772e+00,
         -4.31512939e-02,   6.26145494e-01],
       [ -1.41066127e+00,  -1.98714493e+00,  -1.66148669e+00,
         -8.84348649e-02,   6.47412122e-01],
       [ -7.63876789e-01,  -1.88082147e+00,  -1.42358383e+00,
          2.69028613e-03,   8.54767065e-01],
       [ -2.04241553e+00,  -9.85255030e-01,  -6.48973217e-01,
          4.62619289e-01,  -6.48803295e-01],
       [ -2.02014286e+00,  -9.49321066e-01,  -6.15102286e-01,
          4.73732615e-01,  -6.78472321e-01],
       [ -1.65888586e+00,  -2.70667949e+00,   2.04204498e+00,
          6.65977793e-01,  -2.45567037e-01],
       [ -2.39554758e+00,  -3.15185634e+00,   2.58322939e+00,
          7.89311020e-01,  -2.17025797e-01],
       [ -2.85760122e+00,  -1.57929281e+00,   5.69598277e-03,
          5.99004737e-01,  -5.43716011e-01],
       [ -1.70687235e+00,  -7.76147415e-01,  -7.60829376e-01,
          4.39947937e-01,  -6.76458610e-01],
       [ -1.64493232e+00,  -7.69946694e-01,  -7.36485845e-01,
          4.43164182e-01,  -6.55621500e-01],
       [ -1.82080196e+00,   5.61691632e-01,   1.05420588e-01,
          1.11023467e+00,   2.56369025e-01],
       [ -1.78591475e+00,   5.61942025e-01,   1.15576329e-01,
          1.11250575e+00,   2.63650567e-01],
       [ -1.15465103e+00,   2.50713543e+00,  -9.21367928e-01,
         -1.19796689e+00,   1.47505585e+00],
       [ -1.11649432e+00,   2.50783703e+00,  -9.09791337e-01,
         -1.19554360e+00,   1.48360753e+00],
       [  8.94836252e-01,   1.05284730e+00,   8.24769028e-01,
          6.53549001e-01,  -1.34584820e+00],
       [  9.56815050e-01,   1.06192231e+00,   8.52275708e-01,
          6.56360391e-01,  -1.32105400e+00],
       [  9.86635123e-01,   1.06408154e+00,   8.63089652e-01,
          6.58025887e-01,  -1.31215727e+00],
       [  1.14428642e+00,   1.06914621e+00,   9.13295701e-01,
          6.67731125e-01,  -1.27384848e+00],
       [  1.18843721e+00,   1.07067502e+00,   9.27477183e-01,
          6.70433456e-01,  -1.26296824e+00],
       [  1.76873182e+00,   9.34164563e-01,   1.00135343e+00,
          6.54478210e-01,  -9.17780905e-01],
       [  3.92564491e-01,  -2.43211962e+00,  -5.95154804e-02,
         -4.36798500e-01,  -1.78148820e+00],
       [  3.24209576e-01,  -3.68832804e+00,   1.33577487e+00,
         -5.84972920e-02,   1.07215166e-01],
       [  6.45801788e-01,  -2.11780400e+00,  -4.64555064e-02,
         -4.14026972e-01,  -1.96009442e+00],
       [  7.55179710e-01,  -2.28526729e+00,  -1.39902759e-01,
         -4.56729492e-01,  -1.75108157e+00],
       [  7.45988694e-01,  -2.10971558e+00,  -9.20907651e-03,
         -4.08549603e-01,  -1.92905796e+00],
       [  3.19095121e+00,   3.10747539e+00,   1.48826765e+00,
          4.04372103e-01,   5.65467861e-01],
       [  3.23830439e+00,   3.13958612e+00,   1.44505411e+00,
          3.98266802e-01,   5.52011688e-01],
       [  3.58124111e+00,  -8.92145667e-02,  -6.22766410e-01,
         -1.30924128e+00,  -8.08138260e-01],
       [ -2.30714765e+00,  -2.49503374e+00,   3.03030935e+00,
          4.76234603e-01,   1.82781040e+00],
       [ -9.04100028e-01,   1.85883141e-01,   1.15875387e-01,
         -3.93076123e-01,   4.98699519e-01],
       [ -2.32457401e+00,  -2.84502162e+00,   2.81483919e+00,
          3.47077075e-01,   1.53203886e+00],
       [ -9.21526388e-01,  -1.64104743e-01,  -9.95947701e-02,
         -5.22233651e-01,   2.02927985e-01],
       [ -8.60037194e-01,  -1.63834517e-01,  -8.18827760e-02,
         -5.18206589e-01,   2.15526710e-01],
       [ -1.80619454e+00,  -2.80284494e+00,   2.85319419e+00,
          6.49170320e-01,   1.23793307e+00],
       [ -5.04804119e-01,   1.69491672e-01,  -1.47094760e-01,
         -8.36466572e-01,   4.60979887e-01],
       [ -1.18237247e+00,   3.70297653e+00,   1.39576368e+00,
          4.02560606e-01,   1.18010093e+00],
       [  3.00057374e+00,  -1.29949869e+00,  -1.68530314e+00,
         -6.90013187e-01,  -1.79585802e-01],
       [  3.07093577e+00,  -1.55013285e+00,  -1.80095480e+00,
         -6.02333421e-01,  -5.34741350e-02],
       [  3.13377378e+00,  -1.31490777e+00,  -1.57263499e+00,
         -6.74337980e-01,  -1.07277013e-01],
       [  3.19638482e+00,  -1.56465552e+00,  -1.68950987e+00,
         -5.87296318e-01,   1.85113020e-02],
       [  4.19879721e+00,  -4.81045964e-01,  -2.09400585e+00,
         -7.69282931e-01,  -4.51940180e-01],
       [  4.26499093e+00,  -7.30951319e-01,  -2.21003884e+00,
         -6.81982060e-01,  -3.25655986e-01],
       [  3.66853641e+00,  -1.13648448e+00,  -1.22455060e+00,
         -5.23890780e-01,   1.10839971e-01],
       [  4.63140326e+00,  -4.80924256e-01,  -1.51052983e+00,
         -5.52379821e-01,  -2.15189206e-01],
       [  4.69935463e+00,  -3.22502788e-01,  -1.75384458e+00,
         -3.68183738e-01,   4.28012363e-01],
       [  3.60694282e+00,  -2.83656095e+00,   2.05335899e+00,
         -9.39204108e-01,   1.46963915e+00],
       [  4.40147585e+00,  -8.56459810e-01,  -1.31791439e+00,
         -5.54443686e-01,   2.09136400e-01]])

In [105]:
auto_cleaned_retained.head()

,1,9,10,11,12,13,16,18,19,20,21,22,23,24,25
3,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,3.4,10.0,102.0,5500.0,24,30,13950.0
4,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,3.4,8.0,115.0,5500.0,18,22,17450.0
6,158.0,105.8,192.7,71.4,55.7,2844,136,3.19,3.4,8.5,110.0,5500.0,19,25,17710.0
8,158.0,105.8,192.7,71.4,55.9,3086,131,3.13,3.4,8.3,140.0,5500.0,17,20,23875.0
10,192.0,101.2,176.8,64.8,54.3,2395,108,3.50,2.8,8.8,101.0,5800.0,23,29,16430.0

In [46]:
cov_mat = SS.cov()

In [47]:
cov_mat

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,1.006329,0.521624,-0.523885,-0.338385,-0.220573,-0.478192,-0.253474,-0.110146,-0.258093,-0.021420,-0.139191,-0.003974,0.200366,0.090116,0.150778,-0.163825
1,0.521624,1.006329,-0.060466,0.035766,0.110421,-0.416320,0.126654,0.209135,-0.031758,0.063731,-0.128065,0.292349,0.239201,-0.237014,-0.189758,0.204045
2,-0.523885,-0.060466,1.006329,0.877051,0.820149,0.559285,0.815309,0.653314,0.581818,0.168508,0.293276,0.520219,-0.291065,-0.584332,-0.615622,0.739067
3,-0.338385,0.035766,0.877051,1.006329,0.843644,0.502411,0.876806,0.730548,0.650408,0.121839,0.185984,0.676317,-0.235555,-0.729130,-0.729185,0.765768
4,-0.220573,0.110421,0.820149,0.843644,1.006329,0.294558,0.876105,0.784185,0.576178,0.197863,0.260389,0.686187,-0.233686,-0.670904,-0.697727,0.848708
5,-0.478192,-0.416320,0.559285,0.502411,0.294558,1.006329,0.369375,0.111786,0.256449,-0.091891,0.234785,0.034534,-0.247420,-0.201002,-0.227567,0.246386
6,-0.253474,0.126654,0.815309,0.876806,0.876105,0.369375,1.006329,0.894250,0.649879,0.174945,0.226146,0.795096,-0.261633,-0.766979,-0.794334,0.899295
7,-0.110146,0.209135,0.653314,0.730548,0.784185,0.111786,0.894250,1.006329,0.599507,0.301580,0.141990,0.817212,-0.286488,-0.703564,-0.718615,0.846822
8,-0.258093,-0.031758,0.581818,0.650408,0.576178,0.256449,0.649879,0.599507,1.006329,-0.103230,0.015215,0.563785,-0.314245,-0.594177,-0.594590,0.537269
9,-0.021420,0.063731,0.168508,0.121839,0.197863,-0.091891,0.174945,0.301580,-0.103230,1.006329,0.245128,0.149746,-0.011384,-0.020182,-0.013016,0.161681
10,-0.139191,-0.128065,0.293276,0.185984,0.260389,0.234785,0.226146,0.141990,0.015215,0.245128,1.006329,-0.163332,-0.419406,0.280093,0.222884,0.210687
11,-0.003974,0.292349,0.520219,0.676317,0.686187,0.034534,0.795096,0.817212,0.563785,0.149746,-0.163332,1.006329,0.074526,-0.842513,-0.833181,0.764683
12,0.200366,0.239201,-0.291065,-0.235555,-0.233686,-0.247420,-0.261633,-0.286488,-0.314245,-0.011384,-0.419406,0.074526,1.006329,-0.053264,-0.032985,-0.173004
13,0.090116,-0.237014,-0.584332,-0.729130,-0.670904,-0.201002,-0.766979,-0.703564,-0.594177,-0.020182,0.280093,-0.842513,-0.053264,1.006329,0.978151,-0.696655
14,0.150778,-0.189758,-0.615622,-0.729185,-0.697727,-0.227567,-0.794334,-0.718615,-0.594590,-0.013016,0.222884,-0.833181,-0.032985,0.978151,1.006329,-0.724648
15,-0.163825,0.204045,0.739067,0.765768,0.848708,0.246386,0.899295,0.846822,0.537269,0.161681,0.210687,0.764683,-0.173004,-0.696655,-0.724648,1.006329

In [48]:
eig(cov_mat)

(array([ 7.92170078+0.j,  2.58861152+0.j,  1.58472666+0.j,  1.01391759+0.j,
         0.74993748+0.j,  0.49352927+0.j,  0.42776253+0.j,  0.37464388+0.j,
         0.24712201+0.j,  0.21950317+0.j,  0.14745463+0.j,  0.02123020+0.j,
         0.04512660+0.j,  0.08000832+0.j,  0.09625323+0.j,  0.08973796+0.j]),
 array([[  1.04631332e-01,  -4.04776945e-01,  -2.74899301e-01,
           3.24893216e-01,  -2.00698460e-01,   5.67023745e-01,
          -2.81805314e-01,   2.39873236e-01,  -2.56610823e-01,
          -8.88330468e-02,  -3.12618539e-02,  -3.63781305e-02,
          -5.54559966e-02,  -1.57351306e-01,  -2.01308649e-01,
          -3.05353682e-02],
        [ -4.00627388e-02,  -4.46201934e-01,  -2.80739125e-01,
           1.64838933e-01,  -3.81696699e-01,  -1.73693236e-01,
           6.59471844e-01,  -8.40492088e-03,   2.26242858e-01,
          -6.72456307e-03,  -2.24134321e-02,  -2.31784165e-02,
           3.33580019e-02,   3.65147927e-02,   1.65578506e-01,
           1.85482108e-02],
        [ -3.05343145e-01,   2.12979067e-01,   4.01550878e-03,
          -1.16274034e-01,  -1.67374178e-01,  -1.39070838e-01,
           2.64321524e-01,   1.61186167e-02,  -2.85652529e-01,
          -9.19046535e-02,  -1.34994905e-03,   1.79319778e-02,
          -3.68580752e-02,  -6.78819295e-01,  -4.19676213e-01,
           4.17100315e-02],
        [ -3.26847481e-01,   9.15621690e-02,   3.39147891e-02,
          -2.75312514e-02,  -1.58714542e-01,   6.48502626e-02,
           1.33598015e-01,   1.45347576e-01,  -2.68076382e-01,
          -2.21174462e-02,   5.72743452e-01,  -1.36493337e-01,
           1.06303575e-01,   5.47550621e-01,  -2.90069027e-01,
           1.53917792e-02],
        [ -3.20765301e-01,   3.26024639e-02,  -1.33461126e-01,
          -5.80795055e-03,  -1.11737894e-01,  -1.13460919e-01,
          -1.09367385e-01,  -3.87685910e-02,  -6.10319247e-01,
          -9.83019699e-02,  -1.54441844e-01,   3.65460833e-02,
           8.85159537e-02,   2.43159835e-02,   6.46312725e-01,
          -7.67521473e-02],
        [ -1.35223389e-01,   3.94214503e-01,   2.60078580e-01,
          -1.01797540e-01,  -4.29139797e-01,   5.53032071e-01,
           1.08895362e-01,   9.41110769e-02,   3.26893736e-01,
          -2.03438107e-01,  -1.16678279e-01,  -4.03976818e-03,
           1.18705504e-01,  -2.86871350e-02,   2.46290065e-01,
          -1.16601065e-02],
        [ -3.44240368e-01,   1.51432924e-02,  -8.08922039e-02,
           2.49059933e-02,  -4.76463751e-02,   7.86765631e-03,
          -9.62972653e-02,  -7.91663907e-02,   1.74332962e-01,
          -3.20659035e-02,   6.24040390e-02,   8.75002401e-02,
          -8.66132952e-01,   6.54655331e-02,   4.15104013e-02,
          -2.38886866e-01],
        [ -3.14396934e-01,  -8.38926236e-02,  -2.03050742e-01,
           4.98809206e-02,   2.38289944e-01,   1.61248423e-02,
          -1.09069917e-01,  -1.54006210e-01,   2.75375408e-01,
          -2.31602038e-01,   1.31341216e-01,   1.48199495e-02,
           4.02127524e-01,  -1.18364076e-01,  -5.03138882e-02,
          -6.57687817e-01],
        [ -2.55297173e-01,   4.56896729e-02,   1.67926680e-01,
           3.48019207e-01,   3.07079765e-01,  -1.65986879e-01,
           9.00809703e-02,   7.61384739e-01,   1.03104908e-01,
          -7.29340254e-02,  -2.35336534e-01,  -1.54994093e-02,
           1.95074205e-03,   3.39716022e-02,   2.53257092e-02,
           1.93743011e-02],
        [ -5.69359577e-02,   5.77048312e-03,  -5.01240173e-01,
          -6.27921556e-01,   3.58959337e-01,   2.91873010e-01,
           2.19677733e-01,   2.24066427e-01,  -2.60369903e-03,
           2.71725250e-02,  -1.40089554e-01,  -2.44979864e-02,
          -4.62231781e-02,   7.33114683e-02,   1.12965505e-02,
           1.00413900e-01],
        [ -4.59038258e-02,   3.63866451e-01,  -5.14489636e-01,
           9.96773586e-02,  -3.19106633e-01,  -1.98524266e-01,
          -3.09563905e-01,   1.92449767e-01,   2.20944672e-01,
           4.90008408e-01,   6.94723809e-02,   4.29426726e-02,
           1.27068671e-01,  -5.05045065e-02,   1.02591657e-02,
           4.85134676e-02],
        [ -2.94542196e-01,  -2.66770231e-01,   2.69689756e-02,
          -5.79860918e-02,   1.28656149e-01,   3.73853105e-03,
          -2.41106665e-01,  -3.45551185e-03,   2.60337695e-01,
          -1.38003539e-01,   4.54853524e-01,  -3.37655751e-02,
           5.11086612e-02,  -2.89387819e-01,   2.60139930e-01,
           5.60709690e-01],
        [  8.28884626e-02,  -3.50306317e-01,   2.22361640e-01,
          -5.53401361e-01,  -3.82519109e-01,  -2.92207470e-01,
          -2.94734130e-01,   3.62162797e-01,   5.23619172e-02,
          -8.40915118e-02,  -2.74883711e-02,   1.88031577e-02,
           1.63968264e-02,   4.51002575e-04,  -4.60592573e-02,
          -2.27306428e-01],
        [  2.99077307e-01,   2.28426090e-01,  -2.22983441e-01,
           4.10770172e-02,  -3.38459825e-02,  -1.87291819e-01,
          -4.54942473e-02,   6.16032329e-02,   2.39497453e-02,
          -4.66786752e-01,   9.18803772e-02,  -7.15276055e-01,
          -1.30212731e-01,  -5.01993363e-02,   7.94033391e-02,
          -2.39033328e-02],
        [  3.05483048e-01,   1.92509564e-01,  -2.18944467e-01,
           5.12628971e-02,  -2.72451000e-02,  -1.23247570e-01,
           2.35317174e-02,   1.23130858e-01,  -1.96723752e-02,
          -5.30028777e-01,   2.09434899e-01,   6.73854549e-01,
          -2.42631726e-02,   5.73452792e-02,   3.83451193e-03,
           6.52386305e-02],
        [ -3.19284671e-01,  -4.40628726e-02,  -1.38754112e-01,
           1.48638104e-02,  -1.24035433e-01,  -1.33820632e-01,
          -2.30548739e-01,  -2.52150622e-01,   1.14008853e-01,
          -3.26047639e-01,  -5.21618126e-01,  -9.03492996e-03,
           1.03063855e-01,   3.08150281e-01,  -3.34916110e-01,
           3.42632431e-01]]))

In [49]:
eigen_value = eig(cov_mat)[0]
eigen_value

array([ 7.92170078+0.j,  2.58861152+0.j,  1.58472666+0.j,  1.01391759+0.j,
        0.74993748+0.j,  0.49352927+0.j,  0.42776253+0.j,  0.37464388+0.j,
        0.24712201+0.j,  0.21950317+0.j,  0.14745463+0.j,  0.02123020+0.j,
        0.04512660+0.j,  0.08000832+0.j,  0.09625323+0.j,  0.08973796+0.j])

In [50]:
for i in range(1,17):
    print("Eigen value for", "component",i, " is", eigen_value[i-1])

Eigen value for component 1  is (7.92170078191+0j)
Eigen value for component 2  is (2.58861151621+0j)
Eigen value for component 3  is (1.5847266623+0j)
Eigen value for component 4  is (1.01391759055+0j)
Eigen value for component 5  is (0.749937480869+0j)
Eigen value for component 6  is (0.493529270181+0j)
Eigen value for component 7  is (0.427762529662+0j)
Eigen value for component 8  is (0.374643878333+0j)
Eigen value for component 9  is (0.24712200607+0j)
Eigen value for component 10  is (0.219503165998+0j)
Eigen value for component 11  is (0.147454630643+0j)
Eigen value for component 12  is (0.0212301978286+0j)
Eigen value for component 13  is (0.0451266029061+0j)
Eigen value for component 14  is (0.0800083219201+0j)
Eigen value for component 15  is (0.096253231997+0j)
Eigen value for component 16  is (0.0897379554044+0j)

In [51]:
eigen_vector = eig(cov_mat)[1]
eigen_vector

array([[  1.04631332e-01,  -4.04776945e-01,  -2.74899301e-01,
          3.24893216e-01,  -2.00698460e-01,   5.67023745e-01,
         -2.81805314e-01,   2.39873236e-01,  -2.56610823e-01,
         -8.88330468e-02,  -3.12618539e-02,  -3.63781305e-02,
         -5.54559966e-02,  -1.57351306e-01,  -2.01308649e-01,
         -3.05353682e-02],
       [ -4.00627388e-02,  -4.46201934e-01,  -2.80739125e-01,
          1.64838933e-01,  -3.81696699e-01,  -1.73693236e-01,
          6.59471844e-01,  -8.40492088e-03,   2.26242858e-01,
         -6.72456307e-03,  -2.24134321e-02,  -2.31784165e-02,
          3.33580019e-02,   3.65147927e-02,   1.65578506e-01,
          1.85482108e-02],
       [ -3.05343145e-01,   2.12979067e-01,   4.01550878e-03,
         -1.16274034e-01,  -1.67374178e-01,  -1.39070838e-01,
          2.64321524e-01,   1.61186167e-02,  -2.85652529e-01,
         -9.19046535e-02,  -1.34994905e-03,   1.79319778e-02,
         -3.68580752e-02,  -6.78819295e-01,  -4.19676213e-01,
          4.17100315e-02],
       [ -3.26847481e-01,   9.15621690e-02,   3.39147891e-02,
         -2.75312514e-02,  -1.58714542e-01,   6.48502626e-02,
          1.33598015e-01,   1.45347576e-01,  -2.68076382e-01,
         -2.21174462e-02,   5.72743452e-01,  -1.36493337e-01,
          1.06303575e-01,   5.47550621e-01,  -2.90069027e-01,
          1.53917792e-02],
       [ -3.20765301e-01,   3.26024639e-02,  -1.33461126e-01,
         -5.80795055e-03,  -1.11737894e-01,  -1.13460919e-01,
         -1.09367385e-01,  -3.87685910e-02,  -6.10319247e-01,
         -9.83019699e-02,  -1.54441844e-01,   3.65460833e-02,
          8.85159537e-02,   2.43159835e-02,   6.46312725e-01,
         -7.67521473e-02],
       [ -1.35223389e-01,   3.94214503e-01,   2.60078580e-01,
         -1.01797540e-01,  -4.29139797e-01,   5.53032071e-01,
          1.08895362e-01,   9.41110769e-02,   3.26893736e-01,
         -2.03438107e-01,  -1.16678279e-01,  -4.03976818e-03,
          1.18705504e-01,  -2.86871350e-02,   2.46290065e-01,
         -1.16601065e-02],
       [ -3.44240368e-01,   1.51432924e-02,  -8.08922039e-02,
          2.49059933e-02,  -4.76463751e-02,   7.86765631e-03,
         -9.62972653e-02,  -7.91663907e-02,   1.74332962e-01,
         -3.20659035e-02,   6.24040390e-02,   8.75002401e-02,
         -8.66132952e-01,   6.54655331e-02,   4.15104013e-02,
         -2.38886866e-01],
       [ -3.14396934e-01,  -8.38926236e-02,  -2.03050742e-01,
          4.98809206e-02,   2.38289944e-01,   1.61248423e-02,
         -1.09069917e-01,  -1.54006210e-01,   2.75375408e-01,
         -2.31602038e-01,   1.31341216e-01,   1.48199495e-02,
          4.02127524e-01,  -1.18364076e-01,  -5.03138882e-02,
         -6.57687817e-01],
       [ -2.55297173e-01,   4.56896729e-02,   1.67926680e-01,
          3.48019207e-01,   3.07079765e-01,  -1.65986879e-01,
          9.00809703e-02,   7.61384739e-01,   1.03104908e-01,
         -7.29340254e-02,  -2.35336534e-01,  -1.54994093e-02,
          1.95074205e-03,   3.39716022e-02,   2.53257092e-02,
          1.93743011e-02],
       [ -5.69359577e-02,   5.77048312e-03,  -5.01240173e-01,
         -6.27921556e-01,   3.58959337e-01,   2.91873010e-01,
          2.19677733e-01,   2.24066427e-01,  -2.60369903e-03,
          2.71725250e-02,  -1.40089554e-01,  -2.44979864e-02,
         -4.62231781e-02,   7.33114683e-02,   1.12965505e-02,
          1.00413900e-01],
       [ -4.59038258e-02,   3.63866451e-01,  -5.14489636e-01,
          9.96773586e-02,  -3.19106633e-01,  -1.98524266e-01,
         -3.09563905e-01,   1.92449767e-01,   2.20944672e-01,
          4.90008408e-01,   6.94723809e-02,   4.29426726e-02,
          1.27068671e-01,  -5.05045065e-02,   1.02591657e-02,
          4.85134676e-02],
       [ -2.94542196e-01,  -2.66770231e-01,   2.69689756e-02,
         -5.79860918e-02,   1.28656149e-01,   3.73853105e-03,
         -2.41106665e-01,  -3.45551185e-03,   2.60337695e-01,
         -1.38003539e-01,   4.54853524e-01,  -3.37655751e-02,
          5.11086612e-02,  -2.89387819e-01,   2.60139930e-01,
          5.60709690e-01],
       [  8.28884626e-02,  -3.50306317e-01,   2.22361640e-01,
         -5.53401361e-01,  -3.82519109e-01,  -2.92207470e-01,
         -2.94734130e-01,   3.62162797e-01,   5.23619172e-02,
         -8.40915118e-02,  -2.74883711e-02,   1.88031577e-02,
          1.63968264e-02,   4.51002575e-04,  -4.60592573e-02,
         -2.27306428e-01],
       [  2.99077307e-01,   2.28426090e-01,  -2.22983441e-01,
          4.10770172e-02,  -3.38459825e-02,  -1.87291819e-01,
         -4.54942473e-02,   6.16032329e-02,   2.39497453e-02,
         -4.66786752e-01,   9.18803772e-02,  -7.15276055e-01,
         -1.30212731e-01,  -5.01993363e-02,   7.94033391e-02,
         -2.39033328e-02],
       [  3.05483048e-01,   1.92509564e-01,  -2.18944467e-01,
          5.12628971e-02,  -2.72451000e-02,  -1.23247570e-01,
          2.35317174e-02,   1.23130858e-01,  -1.96723752e-02,
         -5.30028777e-01,   2.09434899e-01,   6.73854549e-01,
         -2.42631726e-02,   5.73452792e-02,   3.83451193e-03,
          6.52386305e-02],
       [ -3.19284671e-01,  -4.40628726e-02,  -1.38754112e-01,
          1.48638104e-02,  -1.24035433e-01,  -1.33820632e-01,
         -2.30548739e-01,  -2.52150622e-01,   1.14008853e-01,
         -3.26047639e-01,  -5.21618126e-01,  -9.03492996e-03,
          1.03063855e-01,   3.08150281e-01,  -3.34916110e-01,
          3.42632431e-01]])

In [158]:
for i in range(1,17):
    print("Eigenvector ", i, ":\n", eigen_vector[:,i-1])

Eigenvector  1 :
 [  3.31167037e-05  -1.22265463e-03  -6.44808622e-04  -1.49009536e-03
  -2.78969499e-04  -9.46624083e-05  -7.31754972e-02  -4.35375433e-03
  -2.42713450e-05  -8.04627437e-06  -1.38565622e-04  -3.96249825e-03
   1.37175322e-02   7.16799418e-04   7.89877593e-04  -9.97204664e-01]
Eigenvector  2 :
 [ -4.81466000e-04  -2.17113034e-02   2.05300277e-03   3.22387258e-03
   4.31327898e-04   1.10338924e-03   1.39217389e-01   1.03881279e-02
   1.40655420e-04  -7.72064030e-06   3.23770921e-03  -1.26013627e-02
  -9.89585538e-01   2.00568072e-03   1.90543103e-03  -2.38011320e-02]
Eigenvector  3 :
 [  1.08038258e-03   7.07231181e-03  -7.41000198e-03  -2.23505297e-02
  -2.22875144e-03  -2.97439600e-03  -9.85215017e-01  -3.92841811e-02
  -4.06608760e-04  -1.05886502e-04   6.85205821e-04  -4.71554688e-02
  -1.40317010e-01   1.12098015e-02   1.18808266e-02   7.07722248e-02]
Eigenvector  4 :
 [ -1.90654746e-02  -9.81690974e-01   2.66357630e-02   2.61714643e-02
   1.58639678e-03   3.03532486e-02   5.85622516e-04  -1.19359181e-01
   3.60723492e-04  -4.07651191e-04   1.22434023e-02  -1.35421616e-01
   2.23069466e-02   1.72767462e-02   7.91659549e-03   2.48343748e-03]
Eigenvector  5 :
 [ 0.00876149 -0.18255387 -0.04945055 -0.02307589 -0.00316223 -0.04151955
 -0.0606066   0.51419185  0.00277768  0.00173767 -0.0913122   0.81938695
 -0.01039148 -0.08678084 -0.08022232 -0.00101437]
Eigenvector  6 :
 [  1.10239689e-03  -3.29324001e-02  -2.60745328e-02  -1.44686062e-01
  -3.04258284e-03  -4.06691711e-02  -4.96575202e-03   8.28900616e-01
  -3.11218211e-03   1.05625205e-02   8.04572127e-02  -5.01303509e-01
   1.53007561e-02   1.27575996e-01   1.18853880e-01  -5.99252939e-04]
Eigenvector  7 :
 [  3.85230583e-02  -2.27730509e-02  -3.04203065e-01  -8.69432559e-01
  -5.76325908e-02  -9.59629061e-02   2.89917096e-02  -1.71685639e-01
  -7.76681904e-03  -8.54263548e-04   9.25158320e-02   1.09061490e-01
  -1.10753995e-03   2.26803545e-01   1.86392848e-01   2.18541256e-05]
Eigenvector  8 :
 [  6.63090469e-04   7.13097161e-03   1.03418818e-01   3.08628979e-01
   3.10253070e-02   5.15881967e-03  -2.92380630e-03  -3.19579319e-02
  -4.42504189e-03   1.59807139e-02   4.61923935e-01   2.02920296e-01
   1.49258923e-03   5.37906841e-01   5.89755039e-01  -1.88068956e-04]
Eigenvector  9 :
 [  3.17400458e-02  -3.37915768e-03   7.05637226e-02  -8.78394833e-02
   5.96830803e-02  -3.87664223e-02  -7.31512619e-03   1.18772137e-02
  -3.14887203e-03   1.60465042e-02   8.61498234e-01   1.89502715e-02
   2.54773252e-04  -2.60478146e-01  -4.12761404e-01  -1.42994301e-04]
Eigenvector  10 :
 [ -2.13139077e-01   1.60164140e-02   9.02049429e-01  -3.27747999e-01
   5.42034955e-02   1.14174721e-01  -1.92065908e-03   6.26239932e-03
   3.05624926e-03   1.49224939e-02  -8.33417289e-02   5.06549843e-02
  -2.77477280e-04   8.40715193e-02  -1.93538065e-02  -1.81267392e-04]
Eigenvector  11 :
 [ -4.52962266e-02  -1.63163198e-02   1.09815568e-01   5.34442937e-02
   2.20075892e-01  -9.62469041e-01   2.98144898e-03  -4.27884215e-02
   1.27828896e-02   1.15300029e-02  -6.20046057e-02  -2.19992302e-02
  -1.30149850e-04   3.04895620e-02  -2.43305177e-02  -3.80558740e-05]
Eigenvector  12 :
 [ -3.24141009e-01   1.08266743e-02  -1.27809777e-01   7.88474038e-02
  -9.04248703e-02   2.39320185e-02  -9.46313792e-04   2.33250359e-03
  -2.93110766e-03  -3.45991253e-02  -4.57637476e-02   8.19949736e-03
  -2.37375438e-04   6.95093086e-01  -6.13991616e-01   7.23151609e-06]
Eigenvector  13 :
 [  6.11832126e-01  -4.74053979e-03   3.65138788e-02  -3.58632568e-02
   7.14994490e-01   1.53581492e-01  -5.50581346e-04   2.02433017e-03
  -1.39558246e-02  -1.32300039e-03  -8.42324194e-02   1.04371201e-03
   3.89691090e-05   2.28255167e-01  -1.69757498e-01  -8.88742698e-05]
Eigenvector  14 :
 [ -6.85631090e-01   1.02710737e-02  -2.09992260e-01  -2.48857669e-02
   6.48850404e-01   1.45421572e-01  -8.09220977e-04   3.56289912e-03
  -8.08440232e-04   1.60562529e-02   2.05723290e-02   3.30480006e-03
  -6.02682264e-05  -1.53024048e-01   1.37156368e-01  -3.21720235e-05]
Eigenvector  15 :
 [ -9.44191998e-03  -8.14991297e-04   1.21696810e-02   3.91507758e-03
  -2.68005462e-04  -1.58090931e-02   3.55278773e-05   3.04796697e-03
  -9.30528654e-01  -3.65053075e-01   2.67598174e-03   1.67426414e-03
  -7.29718922e-05  -1.50757152e-02   1.01437863e-02  -1.26084861e-05]
Eigenvector  16 :
 [  3.63160043e-04   4.43986732e-05  -1.50159819e-02   6.55641541e-03
  -1.88341663e-02   3.53893536e-03   2.47204120e-04  -8.59369497e-03
  -3.65557294e-01   9.29675002e-01  -2.24838080e-02   7.50920483e-04
  -2.30112433e-04   1.53687591e-02  -2.49029090e-02   1.38755876e-05]

In [52]:
total_variance = sum(eigen_value)
total_variance

(16.101265822784825+0j)

In [58]:
variance_five_components = sum(eigen_value[0:6])
variance_five_components

(14.352423302020986+0j)

In [59]:
round(variance_five_components*100/total_variance,5)

(89.138480000000001+0j)

In [60]:
sum(eigen_value[0:1])*100/total_variance

(49.199242277574044+0j)

In [45]:
my_pca.explained_variance_ratio_

array([ 0.49199242,  0.16077068,  0.09842249,  0.0629713 ,  0.04657631])

In [192]:
comps = pd.DataFrame(data=PC1,columns=["C1","C2","C3","C4","C5"])
comps.head()

             C1          C2          C3         C4         C5
0   2482.932197  460.135973 -245.605552  26.859149   6.842623
1   6008.964194  475.558893  -11.673773  23.066916  14.008893
2   6269.700429  478.690998  -10.187134  15.133786  19.630182
3  12435.278135  592.178324 -206.775091   3.218062  17.955466
4   4956.156756  808.574370 -322.131860  41.205966  22.229001

In [189]:
comps_index = comps.set_index(index_list)

In [190]:
comps_index.head()

              C1          C2          C3         C4         C5
3    2482.932197  460.135973 -245.605552  26.859149   6.842623
4    6008.964194  475.558893  -11.673773  23.066916  14.008893
6    6269.700429  478.690998  -10.187134  15.133786  19.630182
8   12435.278135  592.178324 -206.775091   3.218062  17.955466
10   4956.156756  808.574370 -322.131860  41.205966  22.229001

In [172]:
comps.shape,auto_cleaned.shape

((159, 5), (159, 26))

In [191]:
composite_df = pd.concat([auto_cleaned,comps_index], axis=1)
composite_df.head()

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,C1,C2,C3,C4,C5
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,102.0,5500.0,24,30,13950.0,2482.932197,460.135973,-245.605552,26.859149,6.842623
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,115.0,5500.0,18,22,17450.0,6008.964194,475.558893,-11.673773,23.066916,14.008893
6,1,158.0,audi,gas,std,four,sedan,fwd,front,105.8,...,110.0,5500.0,19,25,17710.0,6269.700429,478.690998,-10.187134,15.133786,19.630182
8,1,158.0,audi,gas,turbo,four,sedan,fwd,front,105.8,...,140.0,5500.0,17,20,23875.0,12435.278135,592.178324,-206.775091,3.218062,17.955466
10,2,192.0,bmw,gas,std,two,sedan,rwd,front,101.2,...,101.0,5800.0,23,29,16430.0,4956.156756,808.574370,-322.131860,41.205966,22.229001

In [183]:
index_list = auto_cleaned.index
index_list

Int64Index([  3,   4,   6,   8,  10,  11,  12,  13,  18,  19,
            ...
            195, 196, 197, 198, 199, 200, 201, 202, 203, 204],
           dtype='int64', length=159)

In [193]:
composite_df.shape

(159, 31)

In [ ]:
m = PCA()